# Generated by Django 3.1 on 2020-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cnic', models.CharField(max_length=13)),
                ('program', models.CharField(max_length=9)),
            ],
        ),
    ]
