# Generated by Django 3.1 on 2020-09-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellow',
            old_name='cnic',
            new_name='CNIC',
        ),
    ]
