# Generated by Django 3.1 on 2020-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20200904_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='CNIC',
            field=models.IntegerField(max_length=13),
        ),
    ]
