# Generated by Django 3.1 on 2020-09-05 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20200905_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='CNIC',
            field=models.IntegerField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
