# Generated by Django 3.1 on 2020-09-05 06:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20200905_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='CNIC',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(13)]),
        ),
    ]
