# Generated by Django 3.1 on 2020-09-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_auto_20200905_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='program',
            field=models.CharField(max_length=30),
        ),
    ]
