# Generated by Django 3.1 on 2020-09-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_auto_20200914_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='ID',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
