# Generated by Django 3.1 on 2020-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_fellow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='graduation',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
    ]
